# Generated by Django 5.0.6 on 2024-05-26 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_remove_loan_book_remove_author_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='book_copy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.bookcopy'),
        ),
    ]
